server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-group
    partitions: 3
    replicas: 3
    listener:
      missing-topics-fatal: false

logging:
  level:
    root: info
    com.example.notification_service: debug

  file:
    name: /logs/application.log
