server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: orders-group
    partitions: 3
    replicas: 3
    listener:
      missing-topics-fatal: false

  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
    com.example.order_service: debug

  file:
    name: /logs/application.log
